### ISSUE TITLE
Find Bar and Side Bar are not DPI-aware 

### ISSUE THREAD

**Issue by berlihingen** [ssborbis/ContextSearch-web-ext#313]
which makes both unusable on scaled displays.

**Comment by ssborbis** [comment]
There's page zoom detection using window.`devicePixelRatio` but no DPI compensation. You can set the scale yourself in userstyles. 

Are the menus too small or too big?

```css
#CS_findBarIframe, #CS_sideBarIframe {
    transform: scale( calc(1.5 / var(--cs-zoom))) !important;
}
```
