### ISSUE TITLE
Add a css for Advanced options page

### ISSUE THREAD

**Issue by dnknn** [ssborbis/ContextSearch-web-ext#332]
`chrome-extension://ddippghibegbgpjcaaijbacfhjjeafjh/options.html#advanced`

 **Expected/fixed behavior:** 　　✚

```css
#advancedSettingsTable tr:hover	{background-color:#d7dde6}
#advancedSettingsTable tr:hover td	{color:#00a}
	/* The colors is defined by you ^_^*/
```

> Obviously, this CSS is very useful and can greatly improve the sense of operation.

- Why ❓

Can't  👁perceive which line (`tr`) option at all....

---

## p.s: Can open the CSS customization of the options page and the find bar ?

`chrome-extension://ddippghibegbgpjcaaijbacfhjjeafjh/options.html#general#:~:text=User Styles`

Strictly speaking, it is to open the CSS customization of all pages starting with `chrome-extension://ddippghibegbgpjcaaijbacfhjjeafjh/`

> Currently only the quick menu and sidebar can be CSS.
