### ISSUE TITLE
CSS styles and recommend to try `flex` layout :)

### ISSUE THREAD

**Issue by dnknn** [ssborbis/ContextSearch-web-ext#352]
<details><summary> Ø<s>Done</s>Ø </summary>

```js

```
### Reset the discordant visual appearance
![image](https://user-images.githubusercontent.com/10995302/122699254-a2425a80-d27b-11eb-8333-706113613f36.png)
> Obviously it is not beautiful, it has a double style, so ↴
```css
#editSearchEngineForm input[type=text],
#editSearchEngineForm textarea	{
		outline:none;
		// Do not display the default UA interaction style
		// Because we already custom box-shadow style
		caret-color:blue; 	// :)
}
```

---------------------------------------------------------------------
　　　

### Support all custom CSS styles of our own pages
```
chrome-extension://mlhlcahflgfgallicofkjfedfcgngkno/options.html#general#:~:text=User%20Styles
```

Currently, these 3 pages/document can only be customized: 
```css
	body[data-menu=quickmenu]
	body[data-menu=sidebar]
	body[data-menu=searchbar]
```

---------------------------------------------------------------------
　　　

### `display:flex` is an elegant and flexible layout

- https://developer.mozilla.org/en-US/docs/Web/CSS/flex

> When needed/suitable scene, we can use `flex`, I think it is more flexible and can reduce style maintenance.

```css
body[data-menu=quickmenu] #toolBar,
body[data-menu=sidebar] #toolBar	{
	width:auto!important; // Fix the current problem and use flex layout
	display:flex;align-items:center;justify-content:center;
		// The parent container already has a width, 
		// so I think #toolBar itself does not need to define the width, it will cause unexpected problems
}

		// Here are just some examples :
		// can even continue to specialize like this
#toolBar .tile[data-name=lastused]	{
	flex-grow:.3;
	background-repeat:no-repeat;background-position:center;}

#toolBar .tile	{
	column-gap:5px; // Easily define the column spacing of multiple rows
	// https://caniuse.com/?search=gap
}
```

> I found that in all your styles, none of them use `flex` layout.
I feel that it can handle most scenes, it is not prone to abnormal style problems, so it can reduce style maintenance. `flex` has several keyword properties, but they are all easy to master. When you are familiar with it, you will be surprised to find that it is very flexible for layout, because it is automatically responsive :)

</details>

**Comment by ssborbis** [comment]
> Reset the discordant visual appearance
 
done

>  Support all custom CSS styles of our own pages

What pages, exactly?

> display:flex is an elegant and flexible layout

Maybe try the latest code. I'm not exactly sure what problem you're referring to.

**Comment by dnknn** [comment]
🤝ThankYouVeryMuch!

if our own extension 🆔 is `mlhlcahflgfgallicofkjfedfcgngkno`

> What pages, exactly?

- options
```js
chrome-extension://mlhlcahflgfgallicofkjfedfcgngkno/options.html
```

- findbar iframe
```js
		iframe src
chrome-extension://mlhlcahflgfgallicofkjfedfcgngkno/findbar.html
		document.body
		body>#findbar
```

> Of course this is an unimportant little question, just let you know it is enough. 
If it is easy to support, otherwise please ignore!

**Comment by dnknn** [comment]
@ssborbis 
> Maybe try the latest code. I'm not exactly sure what problem you're referring to.

version V1.29 
![image](https://user-images.githubusercontent.com/10995302/123186682-4110c600-d4cb-11eb-9890-b072a83dd276.png)

**Comment by ssborbis** [comment]
@dnknn 

The sidebar is behaving poorly in chrome right now ( even on the latest from the dev branch ). Not sure what's up, but I'll check it out.

**Comment by dnknn** [comment]
> The sidebar is behaving poorly in chrome right now ( even on the latest from the dev branch ). Not sure what's up, but I'll check it out.

you are right! I just tested it casually and found a big problem.

🕗version: (Latest development version) https://github.com/ssborbis/ContextSearch-web-ext/tree/development. Please see the gif demo 👇

![Bug](https://user-images.githubusercontent.com/10995302/123341724-0a958280-d581-11eb-9680-933b3ec0dec3.gif)

**Comment by dnknn** [comment]
@ssborbis 
> The sidebar is behaving poorly in chrome right now ( even on the latest from the dev branch ). Not sure what's up, but I'll check it out.

you are right! I just tested it casually and found a big problem.

🕗version: (Latest development version) https://github.com/ssborbis/ContextSearch-web-ext/tree/development. Please see the gif demo 👇

![Bug](https://user-images.githubusercontent.com/10995302/123341724-0a958280-d581-11eb-9680-933b3ec0dec3.gif)

　

I think we can fix the problem like this : 

- When you click [see here image](https://user-images.githubusercontent.com/10995302/123341929-64964800-d581-11eb-869c-89c61cb5aafa.png) to switch it, don't change the width.

- That is to say, a uniform fixed width (users can customize the width)

- Please see the gif demo : I think this way is the best.
   * This is version 1.29, I customize (`width` will not change) it with CSS.
![1111](https://user-images.githubusercontent.com/10995302/123342216-ee461580-d581-11eb-8c46-e19328eb58c4.gif)

- There are many benefits of not changing the width
   * e.g. It's not easy to go wrong.
   * e.g. When switching to grid display, the tools icon will not be displayed incompletely (because the width is not enough)
   * e.g. ....


> Below are some issues/Bugs that I used to fix V1.29 version with `CSS`
```css
#CS_sbIframe,		/*AltE*/
#CS_quickMenuIframe	/*E*/
	{min-width:270px}
body[data-menu=searchbar]/*CtrlE*/	{min-width:320px!important}

#CS_sbIframe		{min-height:660px}
#quickMenuElement[data-menu=sidebar]	{min-height:552px}


/*fixed AltE : dragging to width:100% Bug*/
#CS_sbIframe	{max-width:500px;min-height:660px}
body[data-menu=sidebar]>#toolBar	{max-width:550px}
/*fixed AltE incomplete display bug*/
#quickMenuElement[data-menu=sidebar]	{white-space:normal}
#quickMenuElement	{padding-bottom:5px;left:2px!important}

/*fixed E/AltE tools incomplete display bug and use flex layout*/
body[data-menu=quickmenu] #toolBar,
body[data-menu=sidebar] #toolBar	{width:auto!important;
	display:flex;align-items:center;justify-content:center;	
}


#toolBar .tile[data-type=tool]:not([data-name=lastused]):not(:hover)	{opacity:.6}
```
