### ISSUE TITLE
Is it possible to make the outline of the 'quick menu' square?

### ISSUE THREAD

**Issue by c6248** [ssborbis/ContextSearch-web-ext#703]
Thank you for the perfect extension.

Currently, the outline of the quick menu is round shape.
Can I change it to a square?

**Comment by ssborbis** [comment]
CS Options -> General -> User Styles enable and add...

```css
#CS_quickMenuIframe {
    border-radius:0;
}
```
